/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_digipen_androidport_MainActivity */

#ifndef _Included_edu_digipen_androidport_MainActivity
#define _Included_edu_digipen_androidport_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_digipen_androidport_MainActivity
 * Method:    value
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_digipen_androidport_MainActivity_value
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class edu_digipen_androidport_MainActivity_PlaceholderFragment */

#ifndef _Included_edu_digipen_androidport_MainActivity_PlaceholderFragment
#define _Included_edu_digipen_androidport_MainActivity_PlaceholderFragment
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
